json.name @user.name
json.firstname @user.firstname
json.lastname @user.lastname
json.userid @user.userid
json.id @user.id
json.projectids @user.projectids
json.facebook @user.facebook
json.deviceids @user.deviceids
json.primary_color primary_color
json.secondary_color secondary_color
json.tertiary_color tertiary_color